# @package model
type: autoARIMA
name: null
release_dir: null
autoARIMA:
  start_p: 2
  start_q: 2
  max_p: 5
  max_q: 5
  seasonal: true
  start_P: 1
  start_Q: 1
  max_P: 2
  max_Q: 2
  max_d: 2
  max_D: 1
  information_criterion: aic
  suppress_warnings: true
  trace: false
  error_action: ignore
  stepwise: false
  n_jobs: -1
  max_history_length: 336   # 14 days
